export const TASKS_GET_ALL = "TASKS_GET_ALL"
export const TASKS_GET_ALL_FAILED = "TASKS_GET_ALL_FAILED"
export const TASKS_GET_ALL_SUCCESS = "TASKS_GET_ALL_SUCCESS"

export const TASKS_CREATE = "TASKS_CREATE"
export const TASKS_CREATE_FAILED = "TASKS_CREATE_FAILED"
export const TASKS_CREATE_SUCCESS = "TASKS_CREATE_SUCCESS"

export const TASKS_EDIT = "TASKS_EDIT"
export const TASKS_MOVE = "TASKS_MOVE"
export const TASKS_EDIT_FAILED = "TASKS_EDIT_FAILED"
export const TASKS_EDIT_SUCCESS = "TASKS_EDIT_SUCCESS"

export const TASKS_DELETE = "TASKS_DELETE"
export const TASKS_DELETE_FAILED = "TASKS_DELETE_FAILED"
export const TASKS_DELETE_SUCCESS = "TASKS_DELETE_SUCCESS"

export const AUTHENTICATE = "AUTHENTICATE"
export const AUTHENTICATE_FAILED = "AUTHENTICATE_FAILED"
export const AUTHENTICATE_SUCCESS = "AUTHENTICATE_SUCCESS"

export const REGISTER = "REGISTER"
export const REGISTER_FAILED = "REGISTER_FAILED"
export const REGISTER_SUCCESS = "REGISTER_SUCCESS"